title: 'Third Practice New Music Festival'
author:
  name: 'Becky Brown'
  email: bardbarienne@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'a celebration of new media and art'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
