enabled: true
site_title:
  enabled: true
google_fonts_logo:
  enabled: true
fontawesome:
  enabled: true
google_prettify:
  enabled: true
dropdown:
  enabled: true
mobilemenu_breakpoint: large
mobilemenu_position: left
animate_css:
  enabled: true
wow_js:
  enabled: true
css_custom:
  enabled: true
